jwt:
  secretpass: 'az2011indice.comex2077notis'

server:
  port: 8077

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exnotis
    password: ex753kawaei
    username: exnotis
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

exToken:
  own: mfr9u2348jn932g
  followService: efj234jhnfg3
  notificationService: 234rt3t5
  likeService: 234rt423g
  commentService: 4353tgrfg
  accountService: 23rfrweg